name: family_photo_desktop
description: "家庭照片管理桌面端应用"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI组件
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  
  # 状态管理
  get: ^4.6.6
  
  # 网络请求
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  
  # 本地存储
  shared_preferences: ^2.3.2
  sqflite: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Protobuf support
  protobuf: ^3.1.0
  fixnum: ^1.1.0
  
  # 图片处理
  image_picker: ^1.1.2
  photo_manager: ^3.5.0
  cached_network_image: ^3.4.1
  image: ^4.2.0
  
  # 路由导航
  go_router: ^14.6.1
  
  # 工具类
  uuid: ^4.5.1
  intl: ^0.19.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  
  # WebSocket
  web_socket_channel: ^3.0.1
  
  # 文件处理
  file_picker: ^8.1.4
  path: ^1.9.0
  
  # 加密
  crypto: ^3.0.5
  
  # 日志
  logger: ^2.4.0
  
  # 桌面特有依赖
  window_manager: ^0.4.2
  desktop_drop: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 代码生成
  build_runner: ^2.4.13
  retrofit_generator: ^8.2.1
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  
  # 代码规范
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # 资源文件
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  
  # 字体配置
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
