name: family_photo_desktop
description: "家庭照片管理桌面端应用"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

# 桌面端平台配置
platforms:
  windows:
  macos:
  linux:

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # UI组件
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  
  # 状态管理
  get: ^4.6.6
  
  # 网络请求
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  
  # 本地存储 - 桌面端优化
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite_common_ffi: ^2.3.3
  sqlite3: ^2.4.2
  sqlite3_flutter_libs: ^0.5.24
  

  
  # 图片处理 - 桌面端专用
  cached_network_image: ^3.4.1
  image: ^4.2.0
  flutter_svg: ^2.0.10+1
  
  # 路由导航
  go_router: ^14.6.1
  
  # 窗口管理
  # bitsdojo_window: ^0.1.6  # 暂时注释掉，可能导致构建问题
  
  # 国际化
  intl: ^0.20.2
  
  # 工具类
  uuid: ^4.5.1
  path_provider: ^2.1.4
  
  # WebSocket
  web_socket_channel: ^3.0.1
  
  # 文件处理 - 桌面端专用
  file_picker: ^8.1.4
  path: ^1.9.0
  
  # 加密
  crypto: ^3.0.5
  
  # 日志
  logger: ^2.4.0
  
  # 桌面端专用依赖
  window_manager: ^0.4.2
  # desktop_drop: ^0.6.1  # 暂时注释掉，可能导致构建问题
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 代码生成
  build_runner: ^2.4.13
  retrofit_generator: ^8.2.1
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  
  # 代码规范
  flutter_lints: ^5.0.0
  
  # 图标生成
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  generate: true
  
  # 资源文件
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  
  # 字体配置
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700

# flutter_launcher_icons 配置
flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48
